"""Shell tab-completion: the argcomplete marker and the shipped completion files.

Tab-completion is enabled by two independent mechanisms, and both are easy to
break from a distance:

* argcomplete's *global* hook (``activate-global-python-argcomplete``) installs
  a single default completer for every command, but it only completes a console
  script whose entry-point module carries the literal ``PYTHON_ARGCOMPLETE_OK``
  within its first 1024 bytes — see argcomplete's ``_check_console_script``.
  Growing the ``cli`` module docstring would silently push the marker out of
  range and turn completion off with no other symptom.
* Without that hook, what makes Tab work with no user setup at all is the
  completion file ``hatch_build.py`` ships as wheel shared-data. A typo in
  either destination path lands it somewhere the shell never looks, which no
  other test would notice.
"""

import importlib.util
import tomllib
from pathlib import Path

import pytest

import swapsack.cli

ROOT = Path(__file__).resolve().parent.parent

# argcomplete only reads this much of the file when looking for the marker.
MARKER_WINDOW = 1024


def _load_build_hook():
    """Import the root-level ``hatch_build.py``, which is not on sys.path."""
    spec = importlib.util.spec_from_file_location(
        "swapsack_hatch_build", ROOT / "hatch_build.py"
    )
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_cli_module_carries_the_argcomplete_marker():
    # The console script generated by pip/uv is machine-written and cannot hold
    # the marker itself, so argcomplete resolves the entry point and looks in
    # the module instead. Byte offset matters, hence the slice.
    head = Path(swapsack.cli.__file__).read_bytes()[:MARKER_WINDOW]
    assert b"PYTHON_ARGCOMPLETE_OK" in head


def test_completion_snippet_registers_the_swapsack_command():
    hook = _load_build_hook()
    snippet = hook.completion_snippet()

    # Self-contained: it defines the completer and binds it, with no runtime
    # dependency on register-python-argcomplete being installed or on PATH.
    assert "_python_argcomplete" in snippet
    assert "complete -o nospace" in snippet
    assert snippet.rstrip().endswith("fi")
    # The same file doubles as a zsh autoload function, which needs the tag on
    # the very first line.
    assert snippet.startswith("#compdef swapsack")


def test_build_hook_ships_completions_as_shared_data(tmp_path):
    hook = _load_build_hook()
    instance = hook.CompletionBuildHook(
        str(ROOT), {}, None, None, str(tmp_path), "wheel", app=None
    )

    build_data = {"shared_data": {}}
    instance.initialize("standard", build_data)

    # Destinations are relative to the install prefix. bash-completion's dynamic
    # loader resolves the real path of the command and probes
    # <prefix>/share/bash-completion/completions/<cmd>; zsh autoloads from
    # <prefix>/share/zsh/site-functions/_<cmd>.
    assert sorted(build_data["shared_data"].values()) == [
        "share/bash-completion/completions/swapsack",
        "share/zsh/site-functions/_swapsack",
    ]
    for source in build_data["shared_data"]:
        assert Path(source).read_text().startswith("#compdef swapsack")

    sources = list(build_data["shared_data"])
    instance.finalize("standard", build_data, "")
    assert not any(Path(source).exists() for source in sources)


def test_build_hook_is_wired_into_pyproject():
    # A hook that is never registered is a hook that never runs.
    config = tomllib.loads((ROOT / "pyproject.toml").read_text())
    hooks = config["tool"]["hatch"]["build"]["hooks"]
    assert "custom" in hooks, (
        "hatch_build.py is only picked up via [tool.hatch.build.hooks.custom]"
    )

    hook = _load_build_hook()
    assert hook.CompletionBuildHook.PLUGIN_NAME == "custom"

    # argcomplete is a runtime dependency, but the hook imports it at *build*
    # time, where only build-system requires are installed.
    requires = " ".join(config["build-system"]["requires"])
    assert "argcomplete" in requires


@pytest.mark.parametrize("shell", ["bash", "zsh"])
def test_completion_file_names_match_the_console_script(shell):
    # The shell looks the file up by the command's own name; getting this wrong
    # is silent.
    config = tomllib.loads((ROOT / "pyproject.toml").read_text())
    assert "swapsack" in config["project"]["scripts"]

    hook = _load_build_hook()
    destinations = hook.SHARED_DATA.values()
    assert any(dest.endswith("swapsack") and shell in dest for dest in destinations)
