#!/usr/bin/env bash
# Run a swapsack command and append an auditable record of it to a session log.
#
# This exists for live-money sessions: exercising the wallet against mainnet is
# the one kind of testing the unit suite cannot do, and the only durable record
# of what was run (and what the network answered) is what we capture here.
#
#   scripts/live-log.sh balance
#   scripts/live-log.sh swap --from BTC --to ETH --amount 0.001
#   SWAPSACK_LIVE_LOG=/tmp/x.md scripts/live-log.sh quote --from BTC --to ETH ...
#
# Each entry records the wall-clock time, the exact argv, the swapsack version
# and git commit under test, combined stdout+stderr, the exit code and the
# duration. The passphrase is never part of argv (it is prompted on /dev/tty or
# read from $SWAPSACK_PASSPHRASE), so it cannot leak into the log.
#
# Refuses outright to run the three subcommands whose *output* is a secret
# (show-seed, add-hd, add-raw) -- capturing a mnemonic or a private key to a
# file inside a git repository is not recoverable. The default log location is
# gitignored for the same reason.
set -uo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
LOG=${SWAPSACK_LIVE_LOG:-$repo_root/live-sessions/$(date +%F).md}
SWAPSACK=${SWAPSACK_BIN:-$repo_root/.venv/bin/swapsack}

if [ $# -eq 0 ]; then
	echo "usage: $0 <swapsack args...>" >&2
	exit 2
fi

case "$1" in
show-seed | add-hd | add-raw)
	echo "refusing to log '$1': its output is key material. Run it directly." >&2
	exit 2
	;;
esac

mkdir -p "$(dirname "$LOG")"
if [ ! -s "$LOG" ]; then
	{
		echo "# swapsack live session — $(date +%F)"
		echo
		echo "Generated by \`scripts/live-log.sh\`. Every entry is a real command"
		echo "against mainnet: amounts, addresses and txids below are real."
		echo
	} >>"$LOG"
fi

version=$("$SWAPSACK" --version 2>&1 | tail -1)
commit=$(git -C "$repo_root" rev-parse --short HEAD 2>/dev/null || echo unknown)
dirty=$(git -C "$repo_root" status --porcelain 2>/dev/null | head -1)
[ -n "$dirty" ] && commit="$commit-dirty"

# %q-quote argv so the logged line is copy-pasteable and unambiguous.
printf -v cmdline '%q ' "$@"
started=$(date --iso-8601=seconds)
start_s=$(date +%s)

{
	echo "## \`swapsack ${cmdline% }\`"
	echo
	echo "- **when:** $started"
	echo "- **build:** $version (commit \`$commit\`)"
	echo
	echo '```console'
	echo "\$ swapsack ${cmdline% }"
} >>"$LOG"

# Keep stdout/stderr on the terminal (so interactive prompts and confirmations
# still work) while teeing a copy into the log.
"$SWAPSACK" "$@" 2>&1 | tee -a "$LOG"
status=${PIPESTATUS[0]}

{
	echo '```'
	echo
	echo "- **exit:** $status after $(($(date +%s) - start_s))s"
	echo
} >>"$LOG"

echo "[live-log] exit $status -> $LOG" >&2
exit "$status"
